FROM python:3.10-slim


WORKDIR /app
RUN apt-get update && apt-get install -y \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt
RUN pip install --no-cach-dir -r requirement.txt 
COPY . .
EXPOSE 8080

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]